import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialSchema1789952371022 implements MigrationInterface {
    name = 'InitialSchema1789952371022'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query('CREATE EXTENSION IF NOT EXISTS "uuid-ossp"');
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "create_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "profiles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "first_name" character varying, "last_name" character varying, "avatar_url" character varying, "phone" character varying, "timezone" character varying NOT NULL DEFAULT 'UTC', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_9e432b7df0d182f8d292902d1a" UNIQUE ("user_id"), CONSTRAINT "PK_8e520eb4da7dc01d0e190447c8e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "password_hash" character varying, "supabase_user_id" uuid, "email_verified_at" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "UQ_936242eb49f7a22473149590995" UNIQUE ("supabase_user_id"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "accounts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "email" character varying, "status" character varying NOT NULL DEFAULT 'Active', "type" character varying, "owner_id" uuid, "settings" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_5a7a02c20412299d198e097a8fe" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "project_accounts" ("project_id" uuid NOT NULL, "account_id" uuid NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "removed_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_07acb1e5645192c0ad0b8e83b9a" PRIMARY KEY ("project_id", "account_id"))`);
        await queryRunner.query(`CREATE TABLE "projects" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "description" character varying, "platform_name" character varying, "platform_url" character varying, "price_per_hour" numeric(10,2), "status" character varying NOT NULL DEFAULT 'draft', "start_date" date, "end_date" date, "budget" numeric(12,2), "created_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6271df0a7aed1d6c0691ce6ac50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "tasker_payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "amount" numeric(12,2) NOT NULL, "paymentDate" TIMESTAMP WITH TIME ZONE NOT NULL, "tasker_id" uuid NOT NULL, "project_id" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_15154779eb26eeeaac14b547ef7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "taskers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "first_name" character varying, "last_name" character varying, "email" character varying, "phone" character varying, "bank_name" character varying, "account_name" character varying, "account_number" character varying, "skills" text array, "availability_status" character varying NOT NULL DEFAULT 'available', "status" character varying NOT NULL DEFAULT 'Active', "hourly_rate" numeric(10,2), "rating" numeric(2,1) NOT NULL DEFAULT '0', "bio" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_14773e687ebdd304693d30787a" UNIQUE ("user_id"), CONSTRAINT "PK_37c2e996f067382c86dda5a9dd0" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timesheet_entries" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "timesheet_id" uuid NOT NULL, "entry_date" date NOT NULL, "hours_worked" numeric(4,2) NOT NULL, "task_description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_25a8a9b6a96e72864d598563c56" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "timesheets" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "tasker_id" uuid NOT NULL, "project_id" uuid NOT NULL, "account_id" uuid, "week_starting" date NOT NULL, "status" character varying NOT NULL DEFAULT 'draft', "total_hours" numeric(5,2) NOT NULL DEFAULT '0', "submitted_at" TIMESTAMP WITH TIME ZONE, "approved_at" TIMESTAMP WITH TIME ZONE, "approved_by" uuid, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1dc280b68c9353ecce41a34be71" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reports" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "type" character varying NOT NULL, "filters" jsonb, "data" jsonb, "generated_by" uuid NOT NULL, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d9013193989303580053c0b5ef6" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "resource" character varying NOT NULL, "action" character varying NOT NULL, "description" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "title" character varying NOT NULL, "message" character varying, "type" character varying NOT NULL DEFAULT 'info', "is_read" boolean NOT NULL DEFAULT false, "read_at" TIMESTAMP WITH TIME ZONE, "link" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "export_jobs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "type" character varying NOT NULL, "resource" character varying NOT NULL, "filters" jsonb, "status" character varying NOT NULL DEFAULT 'queued', "file_url" character varying, "requested_by" uuid NOT NULL, "completed_at" TIMESTAMP WITH TIME ZONE, "error_message" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3044ce6f1c6af24058ee609e063" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "analytics_metrics" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "placeholder" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_6710bc54d5d07642f917914942d" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "clients" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "company_name" character varying, "billing_address" character varying, "payment_method" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_07a7a09b04e7b035c9d90cf498" UNIQUE ("user_id"), CONSTRAINT "PK_f1ab7cf3a5714dbc6bb4e1c28a4" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "sessions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying NOT NULL, "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "ip_address" character varying, "user_agent" character varying, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_3238ef96f18b355b671619111bc" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_abaa9e068cdd390bc5210f7988" ON "sessions" ("token_hash") `);
        await queryRunner.query(`CREATE TABLE "auth_rate_limits" ("key" character varying NOT NULL, "hits" integer NOT NULL DEFAULT '0', "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, CONSTRAINT "PK_757a482934f0e4bbacfe58d9dad" PRIMARY KEY ("key"))`);
        await queryRunner.query(`CREATE INDEX "IDX_6999cc71407e03c02512aeedd7" ON "auth_rate_limits" ("expires_at") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid, "action" character varying NOT NULL, "resource" character varying, "resource_id" character varying, "details" jsonb, "ip_address" character varying, "user_agent" character varying, "created_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "account_project_taskers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "account_id" uuid NOT NULL, "project_id" uuid NOT NULL, "tasker_id" uuid NOT NULL, "assigned_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "removed_at" TIMESTAMP WITH TIME ZONE, "status" character varying NOT NULL DEFAULT 'active', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "PK_d330f0e0492824a0ec3f1a45eea" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_6d7aa93bc53d3adf5a3711db0c" ON "account_project_taskers" ("account_id", "project_id", "tasker_id") `);
        await queryRunner.query(`CREATE TABLE "admins" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "department" character varying, "access_level" character varying NOT NULL DEFAULT 'standard', "preferences" jsonb NOT NULL DEFAULT '{}', "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "REL_2b901dd818a2a6486994d915a6" UNIQUE ("user_id"), CONSTRAINT "PK_e3b38270c97a854c48d2e80874e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "admin_invitations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "email" character varying NOT NULL, "token" character varying NOT NULL, "role" character varying NOT NULL DEFAULT 'admin', "invited_by_id" uuid NOT NULL, "expires_at" TIMESTAMP NOT NULL, "accepted" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP NOT NULL DEFAULT now(), "updated_at" TIMESTAMP NOT NULL DEFAULT now(), CONSTRAINT "UQ_3648cb96bcc04ac5cbb7ca84c22" UNIQUE ("email"), CONSTRAINT "UQ_e4d2eac5cdf53aed6a8fe397804" UNIQUE ("token"), CONSTRAINT "PK_0c710b9106ea89847bcf62bd3e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "project_taskers" ("project_id" uuid NOT NULL, "tasker_id" uuid NOT NULL, CONSTRAINT "PK_c925826e0b164e5abbee5379966" PRIMARY KEY ("project_id", "tasker_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_f711b5c4532a41016e515b5ba7" ON "project_taskers" ("project_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_4663e15cb9e7db6e0611f7b318" ON "project_taskers" ("tasker_id") `);
        await queryRunner.query(`ALTER TABLE "profiles" ADD CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "accounts" ADD CONSTRAINT "FK_e6c1947a61f955558ccca3f7c46" FOREIGN KEY ("owner_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_accounts" ADD CONSTRAINT "FK_9c829a48dc869de75c2754d54f0" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "project_accounts" ADD CONSTRAINT "FK_914ed0bffedd91f9253db19c083" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "projects" ADD CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080" FOREIGN KEY ("created_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasker_payments" ADD CONSTRAINT "FK_cfd3a9dcd4f05e8a8cb3429eb47" FOREIGN KEY ("tasker_id") REFERENCES "taskers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "tasker_payments" ADD CONSTRAINT "FK_35aa118f0b90e141a8eb827c6de" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "taskers" ADD CONSTRAINT "FK_14773e687ebdd304693d30787a2" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" ADD CONSTRAINT "FK_1619112e6d4c2ba65a676595bbe" FOREIGN KEY ("timesheet_id") REFERENCES "timesheets"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_02e06b763e13677e4c61fd56d86" FOREIGN KEY ("tasker_id") REFERENCES "taskers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_e890b44a3b88da8046e3fb43c03" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_10fd8851ff9f59fc697956fd415" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "timesheets" ADD CONSTRAINT "FK_6cb3dbdf496045a9c1e5172c0dc" FOREIGN KEY ("approved_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reports" ADD CONSTRAINT "FK_9042e8a886f7f83b1de94fee280" FOREIGN KEY ("generated_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "export_jobs" ADD CONSTRAINT "FK_c3007554b0b03796b4b3bf888e6" FOREIGN KEY ("requested_by") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "clients" ADD CONSTRAINT "FK_07a7a09b04e7b035c9d90cf4984" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "sessions" ADD CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "audit_logs" ADD CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_project_taskers" ADD CONSTRAINT "FK_e2682972ee992e24da7f568f642" FOREIGN KEY ("account_id") REFERENCES "accounts"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_project_taskers" ADD CONSTRAINT "FK_8c80b5e594bb35ae52ade83b792" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "account_project_taskers" ADD CONSTRAINT "FK_9b74346c4f2898c8d750ff50f19" FOREIGN KEY ("tasker_id") REFERENCES "taskers"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admins" ADD CONSTRAINT "FK_2b901dd818a2a6486994d915a68" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "admin_invitations" ADD CONSTRAINT "FK_8482bfb22686bf550e12cea4b60" FOREIGN KEY ("invited_by_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_taskers" ADD CONSTRAINT "FK_f711b5c4532a41016e515b5ba76" FOREIGN KEY ("project_id") REFERENCES "projects"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "project_taskers" ADD CONSTRAINT "FK_4663e15cb9e7db6e0611f7b3182" FOREIGN KEY ("tasker_id") REFERENCES "taskers"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "project_taskers" DROP CONSTRAINT "FK_4663e15cb9e7db6e0611f7b3182"`);
        await queryRunner.query(`ALTER TABLE "project_taskers" DROP CONSTRAINT "FK_f711b5c4532a41016e515b5ba76"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`ALTER TABLE "admin_invitations" DROP CONSTRAINT "FK_8482bfb22686bf550e12cea4b60"`);
        await queryRunner.query(`ALTER TABLE "admins" DROP CONSTRAINT "FK_2b901dd818a2a6486994d915a68"`);
        await queryRunner.query(`ALTER TABLE "account_project_taskers" DROP CONSTRAINT "FK_9b74346c4f2898c8d750ff50f19"`);
        await queryRunner.query(`ALTER TABLE "account_project_taskers" DROP CONSTRAINT "FK_8c80b5e594bb35ae52ade83b792"`);
        await queryRunner.query(`ALTER TABLE "account_project_taskers" DROP CONSTRAINT "FK_e2682972ee992e24da7f568f642"`);
        await queryRunner.query(`ALTER TABLE "audit_logs" DROP CONSTRAINT "FK_bd2726fd31b35443f2245b93ba0"`);
        await queryRunner.query(`ALTER TABLE "sessions" DROP CONSTRAINT "FK_085d540d9f418cfbdc7bd55bb19"`);
        await queryRunner.query(`ALTER TABLE "clients" DROP CONSTRAINT "FK_07a7a09b04e7b035c9d90cf4984"`);
        await queryRunner.query(`ALTER TABLE "export_jobs" DROP CONSTRAINT "FK_c3007554b0b03796b4b3bf888e6"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "reports" DROP CONSTRAINT "FK_9042e8a886f7f83b1de94fee280"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_6cb3dbdf496045a9c1e5172c0dc"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_10fd8851ff9f59fc697956fd415"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_e890b44a3b88da8046e3fb43c03"`);
        await queryRunner.query(`ALTER TABLE "timesheets" DROP CONSTRAINT "FK_02e06b763e13677e4c61fd56d86"`);
        await queryRunner.query(`ALTER TABLE "timesheet_entries" DROP CONSTRAINT "FK_1619112e6d4c2ba65a676595bbe"`);
        await queryRunner.query(`ALTER TABLE "taskers" DROP CONSTRAINT "FK_14773e687ebdd304693d30787a2"`);
        await queryRunner.query(`ALTER TABLE "tasker_payments" DROP CONSTRAINT "FK_35aa118f0b90e141a8eb827c6de"`);
        await queryRunner.query(`ALTER TABLE "tasker_payments" DROP CONSTRAINT "FK_cfd3a9dcd4f05e8a8cb3429eb47"`);
        await queryRunner.query(`ALTER TABLE "projects" DROP CONSTRAINT "FK_8a7ccdb94bcc8635f933c8f8080"`);
        await queryRunner.query(`ALTER TABLE "project_accounts" DROP CONSTRAINT "FK_914ed0bffedd91f9253db19c083"`);
        await queryRunner.query(`ALTER TABLE "project_accounts" DROP CONSTRAINT "FK_9c829a48dc869de75c2754d54f0"`);
        await queryRunner.query(`ALTER TABLE "accounts" DROP CONSTRAINT "FK_e6c1947a61f955558ccca3f7c46"`);
        await queryRunner.query(`ALTER TABLE "profiles" DROP CONSTRAINT "FK_9e432b7df0d182f8d292902d1a2"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4663e15cb9e7db6e0611f7b318"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f711b5c4532a41016e515b5ba7"`);
        await queryRunner.query(`DROP TABLE "project_taskers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP TABLE "admin_invitations"`);
        await queryRunner.query(`DROP TABLE "admins"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6d7aa93bc53d3adf5a3711db0c"`);
        await queryRunner.query(`DROP TABLE "account_project_taskers"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_6999cc71407e03c02512aeedd7"`);
        await queryRunner.query(`DROP TABLE "auth_rate_limits"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_abaa9e068cdd390bc5210f7988"`);
        await queryRunner.query(`DROP TABLE "sessions"`);
        await queryRunner.query(`DROP TABLE "clients"`);
        await queryRunner.query(`DROP TABLE "analytics_metrics"`);
        await queryRunner.query(`DROP TABLE "export_jobs"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP TABLE "reports"`);
        await queryRunner.query(`DROP TABLE "timesheets"`);
        await queryRunner.query(`DROP TABLE "timesheet_entries"`);
        await queryRunner.query(`DROP TABLE "taskers"`);
        await queryRunner.query(`DROP TABLE "tasker_payments"`);
        await queryRunner.query(`DROP TABLE "projects"`);
        await queryRunner.query(`DROP TABLE "project_accounts"`);
        await queryRunner.query(`DROP TABLE "accounts"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TABLE "profiles"`);
        await queryRunner.query(`DROP TABLE "roles"`);
    }

}
